# Generated by Django 5.0.1 on 2024-03-01 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appescola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='acoes',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(default='tste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nascimento',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
