# Generated by Django 5.0.1 on 2024-03-07 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appescola', '0003_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.AddField(
            model_name='nota',
            name='aluno_matriculado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='appescola.aluno'),
        ),
    ]
