# Generated by Django 5.0.1 on 2024-03-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appescola', '0004_remove_nota_aluno_nota_aluno_matriculado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='aluno_matriculado',
            new_name='matricula',
        ),
    ]
